<?php
//$Id: context_admin_vbo.module,v 1.2 2010/03/11 04:42:45 eclipsegc Exp $

/**
 * Implementation of hook_views_api().
 */
function context_admin_vbo_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'context_admin_vbo') . '/includes',
  );
}

function context_admin_vbo_ctools_plugin_directory($module, $plugin) {
  if ($module == 'context_admin') {
    return 'plugins/' . $plugin;
  }
}

